### PR TITLE
Change server to run on HTTPS to allow for Nest Client app. redirect …

### LINKED ISSUE #1: Redirect URL
The Nest Client settings only allows HTTPS redirect URL

### PR DESCRIPTION
**Pull request by ikb42**
…HTTPS URI

Fixes #1

### CODE REVIEW

**Comment by ikb42** [comment]
I signed it!

**Comment by ryanseys** [comment]
Thanks for this. We're hoping once the server-side fix goes out to the Developer Portal, this won't be necessary, however I will keep this open until I hear more about the state of that fix. If it is decided to not go ahead with allowing http for development environments, I will merge this in.

**Comment by ikb42** [comment]
Great stuff thanks

**Comment by ryanseys** [comment]
This bug should be fixed in the Developer Portal. Try it out and let me know! :smile:

**Pull request closed without merging**
